### ISSUE TITLE
Issue with the order of whats displayed in the command line

### ISSUE THREAD

**Issue by nathan-a-macleod** [jacob-macleod/Shelly-Terminal-Shell#1]
When I run `main.py`, the following happens:

When I type something in, it appears as `[A command I typed in] >>>` - the `>>>` appears after the input. 

It should be: `>>> [A command I typed in]`

**Comment by jacob-macleod** [comment]
Thank you for opening this issue, Nathan. My team will get back to you on this one A.S.A.P!

**Comment by jacob-macleod** [comment]
Thank you Nathan, this bug should be fixed
