### ISSUE TITLE
Develop git support for 'default_plugin_core.py'

### ISSUE THREAD

**Issue by jacob-macleod** [jacob-macleod/Shelly-Terminal-Shell#5]
Git support needs to be added to the default core plugin! Perhaps so that it displays username@directory git:(branch) if it detects you are in a git repo. 

Anyone can help with this - perhaps @nathan-a-macleod?

**Comment by nathan-a-macleod** [comment]
I will see if I can implement this, but I am not entirely sure how to do it.
To detect if you are in a git repo, you can probably just do `os.popen("git branch").read().split("\n")[0]` - example output: `* master` - but I don't entirely know how to implement that.

**Comment by jacob-macleod** [comment]
Whatever, I've done it
Only joking, I don't mind
